tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-error": "#490006",
                "on-surface-variant": "#aaaab7",
                "tertiary-container": "#a38efc",
                "error-dim": "#d7383b",
                "on-primary-fixed": "#000000",
                "error": "#ff716c",
                "secondary-fixed": "#d8caff",
                "surface-bright": "#282b3a",
                "surface": "#0c0e17",
                "secondary-dim": "#7e51ff",
                "tertiary-fixed-dim": "#a894ff",
                "on-surface": "#f0f0fd",
                "inverse-on-surface": "#53545f",
                "outline-variant": "#464752",
                "on-secondary": "#25006b",
                "surface-dim": "#0c0e17",
                "surface-variant": "#222532",
                "inverse-surface": "#faf8ff",
                "surface-tint": "#ff88b5",
                "primary-fixed": "#ff6eaa",
                "primary": "#ff88b5",
                "on-primary-fixed-variant": "#5c0031",
                "tertiary-fixed": "#b5a4ff",
                "surface-container-low": "#11131d",
                "inverse-primary": "#ba0069",
                "on-tertiary-container": "#22006d",
                "surface-container": "#171924",
                "surface-container-lowest": "#000000",
                "outline": "#737580",
                "on-tertiary-fixed": "#190057",
                "background": "#0c0e17",
                "surface-container-highest": "#222532",
                "on-tertiary-fixed-variant": "#3c238e",
                "primary-fixed-dim": "#ff4e9f",
                "surface-container-high": "#1c1f2b",
                "primary-dim": "#e10181",
                "on-error-container": "#ffa8a3",
                "on-primary-container": "#4b0027",
                "on-primary": "#610034",
                "on-secondary-fixed-variant": "#591bdc",
                "on-background": "#f0f0fd",
                "tertiary-dim": "#a38efc",
                "on-secondary-fixed": "#3b00a0",
                "error-container": "#9f0519",
                "secondary-container": "#591adc",
                "secondary": "#a68cff",
                "secondary-fixed-dim": "#cabaff",
                "primary-container": "#ff6eaa",
                "on-tertiary": "#2e0f81",
                "on-secondary-container": "#e4daff",
                "tertiary": "#b09eff",
                "neon-green": "#92ff75"
            },
            "borderRadius": {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            "fontFamily": {
                "pixel": ["PixelFont8x8"],
                "SFPro": ["SFProDisplayRegular"],
            }
        },
    },
}